# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anmho < Formula
  desc ""
  homepage "https://github.com/anmho/go-template-cli"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anmho/go-template-cli/releases/download/v0.1.6/go-template-cli_Darwin_x86_64.tar.gz"
      sha256 "d037773180b122ca3ac0e000f3ac0164a93ff7dfd63e89b574626aeaf82f8a20"

      def install
        bin.install "go-template-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anmho/go-template-cli/releases/download/v0.1.6/go-template-cli_Darwin_arm64.tar.gz"
      sha256 "e53f401b2173394039783d0de974d3e4183d8326c1a8bfd3aeaf476f234ed3d7"

      def install
        bin.install "go-template-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anmho/go-template-cli/releases/download/v0.1.6/go-template-cli_Linux_x86_64.tar.gz"
        sha256 "fb36fcc58e4444521ec62ccc6a34617ccfd369c024786f08bd10a74a76ae12e6"

        def install
          bin.install "go-template-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anmho/go-template-cli/releases/download/v0.1.6/go-template-cli_Linux_arm64.tar.gz"
        sha256 "9b8fec46fe9487195dd59c1384484927aab2352c6c02fe88e7e758c5fff4896d"

        def install
          bin.install "go-template-cli"
        end
      end
    end
  end
end
