# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CreateGoApp < Formula
  desc ""
  homepage "https://github.com/anmho/create-go-app"
  version "1.0.18"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anmho/create-go-app/releases/download/v1.0.18/create-go-app_Darwin_x86_64.tar.gz"
      sha256 "cb3ffd281a104225c9379bf4697db936cf7cbf601e9a95ea222a017bfe60cb8c"

      def install
        bin.install "create-go-app"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anmho/create-go-app/releases/download/v1.0.18/create-go-app_Darwin_arm64.tar.gz"
      sha256 "622950a79e2e48689ba931199f19e555ad62ebbc752b842053a0f07805c42cc2"

      def install
        bin.install "create-go-app"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anmho/create-go-app/releases/download/v1.0.18/create-go-app_Linux_x86_64.tar.gz"
        sha256 "65f0936bd81c9eac276cb2a7fbed10dc83067cf3126919832482185262a3ca7f"

        def install
          bin.install "create-go-app"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anmho/create-go-app/releases/download/v1.0.18/create-go-app_Linux_arm64.tar.gz"
        sha256 "8f0f622661320665f95f6fb6b63c718ed9086e0e8cbeecef6264d9a77843c97b"

        def install
          bin.install "create-go-app"
        end
      end
    end
  end
end
