# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CreateGoApp < Formula
  desc ""
  homepage "https://github.com/anmho/create-go-app"
  version "0.1.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anmho/create-go-app/releases/download/v0.1.15/create-go-app_Darwin_x86_64.tar.gz"
      sha256 "13b389162d8406b8758c2b3660ecad55ff5238f9ecdb04865dea8801dd413a9e"

      def install
        bin.install "create-go-app"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anmho/create-go-app/releases/download/v0.1.15/create-go-app_Darwin_arm64.tar.gz"
      sha256 "1a5351ba9fefdf7510ba75b07e27e54fd7e52255078b79ba5caff015cda72f6d"

      def install
        bin.install "create-go-app"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anmho/create-go-app/releases/download/v0.1.15/create-go-app_Linux_x86_64.tar.gz"
        sha256 "a9ad81d029cae2ce1de8d4edcfb359d23ff7225f525b479dc7e1dde7bcc38e8c"

        def install
          bin.install "create-go-app"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anmho/create-go-app/releases/download/v0.1.15/create-go-app_Linux_arm64.tar.gz"
        sha256 "96386cd497ad373c4b378423ee38b875d23d8d0e4294930d4be7ee68eb480724"

        def install
          bin.install "create-go-app"
        end
      end
    end
  end
end
