# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTemplateCli < Formula
  desc ""
  homepage "https://github.com/anmho/go-template-cli"
  version "0.1.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anmho/go-template-cli/releases/download/v0.1.14/go-template-cli_Darwin_x86_64.tar.gz"
      sha256 "6aebf26dacdaee4d3421352322f9ea670be76bb7ce1a449afe064fa99ae95036"

      def install
        bin.install "go-template-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anmho/go-template-cli/releases/download/v0.1.14/go-template-cli_Darwin_arm64.tar.gz"
      sha256 "4802ef3f410e763dcab888df75e847103c447338b7b0e6177d3e27c92dc79f43"

      def install
        bin.install "go-template-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anmho/go-template-cli/releases/download/v0.1.14/go-template-cli_Linux_x86_64.tar.gz"
        sha256 "eda302708367e0b4f752db54f38830e11b6ba3f10bc4ee57198c175de8ae8a8b"

        def install
          bin.install "go-template-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anmho/go-template-cli/releases/download/v0.1.14/go-template-cli_Linux_arm64.tar.gz"
        sha256 "0aa073cb415c41755ebaffc4f73b0bfff485d12b79d4178e8b3df6411cf5391e"

        def install
          bin.install "go-template-cli"
        end
      end
    end
  end
end
