# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTemplateCli < Formula
  desc ""
  homepage "https://github.com/anmho/go-template-cli"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anmho/go-template-cli/releases/download/v0.1.7/go-template-cli_Darwin_x86_64.tar.gz"
      sha256 "c78a46286947ecea8876414c203eb8e509f9071285b2ffb151c63b6b0bbb6c4f"

      def install
        bin.install "go-template-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anmho/go-template-cli/releases/download/v0.1.7/go-template-cli_Darwin_arm64.tar.gz"
      sha256 "eb1b9605b2e226ad1462692e9e2599825e6ca1adefd398a4cc7bc96422dbb6c1"

      def install
        bin.install "go-template-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anmho/go-template-cli/releases/download/v0.1.7/go-template-cli_Linux_x86_64.tar.gz"
        sha256 "7601234f31584535bf11ef529b94656ffdbbe12cdacee620bab6b558483d13a6"

        def install
          bin.install "go-template-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anmho/go-template-cli/releases/download/v0.1.7/go-template-cli_Linux_arm64.tar.gz"
        sha256 "23ebcfb15f23e9ae9723f7f53581f99b95ad2aece2be03c4b2bb54fa17fb0572"

        def install
          bin.install "go-template-cli"
        end
      end
    end
  end
end
